import Header from "@/components/Header";
import "./globals.css";
import { Poppins, Ubuntu } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "300", "400", "500", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} overflow-x-hidden`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
