/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.12 laptop.gltf --types
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    logo_apple_1: THREE.Mesh;
    logo_apple_2: THREE.Mesh;
    connector: THREE.Mesh;
    screen_1: THREE.Mesh;
    green_light: THREE.Mesh;
    black_border_notch_screen: THREE.Mesh;
    grey_border_creen: THREE.Mesh;
    Rectangle_1: THREE.Mesh;
    metalic_screen: THREE.Mesh;
    camera: THREE.Mesh;
    border_black_camera: THREE.Mesh;
    base_2: THREE.Mesh;
    Rectangle_2: THREE.Mesh;
    Rectangle_3: THREE.Mesh;
    Subdiv_3: THREE.Mesh;
    Subdiv_3_1: THREE.Mesh;
    Subdiv_3_2: THREE.Mesh;
    Subdiv_3_3: THREE.Mesh;
    Subdiv_2: THREE.Mesh;
    Subdiv_2_1: THREE.Mesh;
    Subdiv: THREE.Mesh;
    Cylinder: THREE.Mesh;
    mesh_25_instance_1: THREE.Mesh;
    mesh_26_instance_1: THREE.Mesh;
    mesh_26_instance_2: THREE.Mesh;
    mesh_26_instance_3: THREE.Mesh;
    mesh_27_instance_1: THREE.Mesh;
    mesh_27_instance_2: THREE.Mesh;
    mesh_27_instance_3: THREE.Mesh;
    mesh_27_instance_4: THREE.Mesh;
    mesh_27_instance_5: THREE.Mesh;
    mesh_27_instance_6: THREE.Mesh;
    mesh_27_instance_7: THREE.Mesh;
    mesh_27_instance_8: THREE.Mesh;
    mesh_27_instance_9: THREE.Mesh;
    mesh_27_instance_10: THREE.Mesh;
    mesh_28_instance_1: THREE.Mesh;
    mesh_28_instance_2: THREE.Mesh;
    mesh_28_instance_3: THREE.Mesh;
    mesh_28_instance_4: THREE.Mesh;
    mesh_28_instance_5: THREE.Mesh;
    mesh_28_instance_6: THREE.Mesh;
    mesh_28_instance_7: THREE.Mesh;
    mesh_28_instance_8: THREE.Mesh;
    mesh_28_instance_9: THREE.Mesh;
    mesh_28_instance_10: THREE.Mesh;
    mesh_28_instance_11: THREE.Mesh;
    mesh_29_instance_1: THREE.Mesh;
    mesh_29_instance_2: THREE.Mesh;
    mesh_29_instance_3: THREE.Mesh;
    mesh_29_instance_4: THREE.Mesh;
    mesh_29_instance_5: THREE.Mesh;
    mesh_29_instance_6: THREE.Mesh;
    mesh_29_instance_7: THREE.Mesh;
    mesh_29_instance_8: THREE.Mesh;
    mesh_29_instance_9: THREE.Mesh;
    mesh_29_instance_10: THREE.Mesh;
    mesh_29_instance_11: THREE.Mesh;
    mesh_29_instance_12: THREE.Mesh;
    mesh_29_instance_13: THREE.Mesh;
    mesh_44_instance_1: THREE.Mesh;
    mesh_44_instance_2: THREE.Mesh;
    mesh_44_instance_3: THREE.Mesh;
    mesh_44_instance_4: THREE.Mesh;
    mesh_44_instance_5: THREE.Mesh;
    mesh_44_instance_6: THREE.Mesh;
    mesh_44_instance_7: THREE.Mesh;
    mesh_44_instance_8: THREE.Mesh;
    mesh_44_instance_9: THREE.Mesh;
    mesh_44_instance_10: THREE.Mesh;
    mesh_44_instance_11: THREE.Mesh;
    mesh_44_instance_12: THREE.Mesh;
    mesh_44_instance_13: THREE.Mesh;
    mesh_45_instance_1: THREE.Mesh;
    mesh_45_instance_2: THREE.Mesh;
    mesh_45_instance_3: THREE.Mesh;
    mesh_45_instance_4: THREE.Mesh;
    mesh_45_instance_5: THREE.Mesh;
    mesh_45_instance_6: THREE.Mesh;
    mesh_45_instance_7: THREE.Mesh;
    mesh_45_instance_8: THREE.Mesh;
    mesh_45_instance_9: THREE.Mesh;
    mesh_45_instance_10: THREE.Mesh;
    mesh_45_instance_11: THREE.Mesh;
    mesh_45_instance_12: THREE.Mesh;
    mesh_45_instance_13: THREE.Mesh;
    Torus: THREE.Mesh;
    keybord_lign: THREE.Mesh;
    keybord_lign_1: THREE.Mesh;
    keybord_lign_2: THREE.Mesh;
    keybord_lign_3: THREE.Mesh;
    keybord_lign_4: THREE.Mesh;
    Rectangle_6: THREE.Mesh;
    Rectangle_7: THREE.Mesh;
    Rectangle_5: THREE.Mesh;
    Rectangle_14: THREE.Mesh;
    Rectangle_13: THREE.Mesh;
    Rectangle_12: THREE.Mesh;
    Rectangle_11: THREE.Mesh;
    Rectangle_8: THREE.Mesh;
    Rectangle_4: THREE.Mesh;
    Rectangle_9: THREE.Mesh;
    Rectangle_3_1: THREE.Mesh;
    Rectangle_10: THREE.Mesh;
    Rectangle_2_1: THREE.Mesh;
    Rectangle_15: THREE.Mesh;
    keybord_lign_5: THREE.Mesh;
    keybord_lign_6: THREE.Mesh;
    keyboard_1: THREE.Mesh;
    trackpad_top: THREE.Mesh;
    trackpad_border: THREE.Mesh;
    Rectangle_9_1: THREE.Mesh;
    Rectangle_10_1: THREE.Mesh;
    Rectangle_9_2: THREE.Mesh;
    Rectangle_8_1: THREE.Mesh;
    Rectangle_8_2: THREE.Mesh;
    Rectangle_3_2: THREE.Mesh;
    Ellipse: THREE.Mesh;
    Rectangle_6_1: THREE.Mesh;
    Rectangle_5_1: THREE.Mesh;
    Rectangle_4_1: THREE.Mesh;
    Cube: THREE.Mesh;
    Rectangle: THREE.Mesh;
  };
  materials: {};
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/laptop.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[-38.08, 194.69, -211.88]}
          rotation={[-2.41, -0.46, 3.12]}
          scale={0.39}
        >
          <group position={[-1.27, -436.61, -17.86]}>
            <group
              position={[-6.96, 478.11, 16.32]}
              scale={[1.96, 1.96, 1089621.13]}
            >
              <mesh
                geometry={nodes.logo_apple_1.geometry}
                material={nodes.logo_apple_1.material}
                position={[-22.72, 24.79, 0]}
                scale={[0.09, 0.09, 0]}
              />
              <mesh
                geometry={nodes.logo_apple_2.geometry}
                material={nodes.logo_apple_2.material}
                position={[0.14, 47.16, 0]}
                scale={[0.09, 0.09, 0]}
              />
            </group>
            <mesh
              geometry={nodes.connector.geometry}
              material={nodes.connector.material}
              position={[1.27, -20.52, -5.61]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={2.07}
            />
            <mesh
              geometry={nodes.screen_1.geometry}
              material={nodes.screen_1.material}
              position={[669.2, 44.16, 0.66]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={0.9}
            />
            <mesh
              geometry={nodes.green_light.geometry}
              material={nodes.green_light.material}
              position={[-25.41, 906.02, 0.61]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.82, 0.81, 0.92]}
            />
            <mesh
              geometry={nodes.black_border_notch_screen.geometry}
              material={nodes.black_border_notch_screen.material}
              position={[691.33, 915.76, 0.97]}
              rotation={[-Math.PI, 0, Math.PI]}
              scale={[0.9, 0.9, 1]}
            />
            <mesh
              geometry={nodes.grey_border_creen.geometry}
              material={nodes.grey_border_creen.material}
              position={[0.45, 448.36, 9.16]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.9, 0.9, 1]}
            />
            <mesh
              geometry={nodes.Rectangle_1.geometry}
              material={nodes.Rectangle_1.material}
              position={[0, 448.36, 15.07]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.9, 0.9, 1]}
            />
            <mesh
              geometry={nodes.metalic_screen.geometry}
              material={nodes.metalic_screen.material}
              position={[0, 448.36, 10.17]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.9, 0.9, 1]}
            />
            <mesh
              geometry={nodes.camera.geometry}
              material={nodes.camera.material}
              position={[-3.46, 906.02, 0.61]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.82, 0.81, 0.92]}
            />
            <mesh
              geometry={nodes.border_black_camera.geometry}
              material={nodes.border_black_camera.material}
              position={[-3.46, 906.02, 0.84]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={[0.82, 0.81, 0.92]}
            />
          </group>
          <group position={[-56.34, -457.52, -546.11]}>
            <group
              position={[5.42, -7.13, -0.41]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.base_2.geometry}
                material={nodes.base_2.material}
                position={[10.98, 13.35, 134.94]}
              />
            </group>
            <group
              position={[1.28, 32.07, 180.03]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Rectangle_2.geometry}
                material={nodes.Rectangle_2.material}
                position={[585.27, 0.3, -16.44]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Rectangle_3.geometry}
                material={nodes.Rectangle_3.material}
                position={[-697.58, 0.3, -16.44]}
                rotation={[-Math.PI / 2, 0, -Math.PI]}
              />
            </group>
            <group
              position={[51.91, -18.23, -11.95]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Subdiv_3.geometry}
                material={nodes.Subdiv_3.material}
                position={[466.78, 3.42, -412.46]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1.09, 1.15, 1.13]}
              />
              <mesh
                geometry={nodes.Subdiv_3_1.geometry}
                material={nodes.Subdiv_3_1.material}
                position={[466.78, -2.64, -412.46]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1, 1.05, 1.03]}
              />
              <mesh
                geometry={nodes.Subdiv_3_2.geometry}
                material={nodes.Subdiv_3_2.material}
                position={[-466.78, 3.42, -412.46]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1.09, 1.15, 1.13]}
              />
              <mesh
                geometry={nodes.Subdiv_3_3.geometry}
                material={nodes.Subdiv_3_3.material}
                position={[-464, -3.76, -412.39]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1, 1.05, 1.03]}
              />
              <mesh
                geometry={nodes.Subdiv_2.geometry}
                material={nodes.Subdiv_2.material}
                position={[466.78, 3.42, 326.82]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1.09, 1.15, 1.13]}
              />
              <mesh
                geometry={nodes.Subdiv_2_1.geometry}
                material={nodes.Subdiv_2_1.material}
                position={[466.78, -2.64, 326.82]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1, 1.05, 1.03]}
              />
              <mesh
                geometry={nodes.Subdiv.geometry}
                material={nodes.Subdiv.material}
                position={[-466.78, 3.42, 326.82]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1.09, 1.15, 1.13]}
              />
              <mesh
                geometry={nodes.Cylinder.geometry}
                material={nodes.Cylinder.material}
                position={[-466.78, -2.64, 326.82]}
                rotation={[0, 0, -Math.PI]}
                scale={[-1, 1.05, 1.03]}
              />
            </group>
            <group
              position={[57.79, 37.67, 198.94]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <group
                position={[-550.66, -9.04, 198.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.mesh_26_instance_1.geometry}
                  material={nodes.mesh_26_instance_1.material}
                />
                <mesh
                  geometry={nodes.mesh_26_instance_2.geometry}
                  material={nodes.mesh_26_instance_2.material}
                  position={[81, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_26_instance_3.geometry}
                  material={nodes.mesh_26_instance_3.material}
                  position={[162, 0, 0]}
                />
              </group>
              <group
                position={[-364.4, -9.04, 120.03]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.mesh_27_instance_1.geometry}
                  material={nodes.mesh_27_instance_1.material}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_2.geometry}
                  material={nodes.mesh_27_instance_2.material}
                  position={[81, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_3.geometry}
                  material={nodes.mesh_27_instance_3.material}
                  position={[162, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_4.geometry}
                  material={nodes.mesh_27_instance_4.material}
                  position={[243, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_5.geometry}
                  material={nodes.mesh_27_instance_5.material}
                  position={[324, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_6.geometry}
                  material={nodes.mesh_27_instance_6.material}
                  position={[405, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_7.geometry}
                  material={nodes.mesh_27_instance_7.material}
                  position={[486, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_8.geometry}
                  material={nodes.mesh_27_instance_8.material}
                  position={[567, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_9.geometry}
                  material={nodes.mesh_27_instance_9.material}
                  position={[648, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_27_instance_10.geometry}
                  material={nodes.mesh_27_instance_10.material}
                  position={[729, 0, 0]}
                />
              </group>
              <group
                position={[-405.8, -9.04, 40.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.mesh_28_instance_1.geometry}
                  material={nodes.mesh_28_instance_1.material}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_2.geometry}
                  material={nodes.mesh_28_instance_2.material}
                  position={[81, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_3.geometry}
                  material={nodes.mesh_28_instance_3.material}
                  position={[162, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_4.geometry}
                  material={nodes.mesh_28_instance_4.material}
                  position={[243, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_5.geometry}
                  material={nodes.mesh_28_instance_5.material}
                  position={[324, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_6.geometry}
                  material={nodes.mesh_28_instance_6.material}
                  position={[405, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_7.geometry}
                  material={nodes.mesh_28_instance_7.material}
                  position={[486, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_8.geometry}
                  material={nodes.mesh_28_instance_8.material}
                  position={[567, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_9.geometry}
                  material={nodes.mesh_28_instance_9.material}
                  position={[648, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_10.geometry}
                  material={nodes.mesh_28_instance_10.material}
                  position={[729, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_28_instance_11.geometry}
                  material={nodes.mesh_28_instance_11.material}
                  position={[810, 0, 0]}
                />
              </group>
              <group
                position={[-429.33, -9.04, -40.64]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.mesh_29_instance_1.geometry}
                  material={nodes.mesh_29_instance_1.material}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_2.geometry}
                  material={nodes.mesh_29_instance_2.material}
                  position={[81, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_3.geometry}
                  material={nodes.mesh_29_instance_3.material}
                  position={[162, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_4.geometry}
                  material={nodes.mesh_29_instance_4.material}
                  position={[243, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_5.geometry}
                  material={nodes.mesh_29_instance_5.material}
                  position={[324, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_6.geometry}
                  material={nodes.mesh_29_instance_6.material}
                  position={[405, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_7.geometry}
                  material={nodes.mesh_29_instance_7.material}
                  position={[486, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_8.geometry}
                  material={nodes.mesh_29_instance_8.material}
                  position={[567, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_9.geometry}
                  material={nodes.mesh_29_instance_9.material}
                  position={[648, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_10.geometry}
                  material={nodes.mesh_29_instance_10.material}
                  position={[729, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_11.geometry}
                  material={nodes.mesh_29_instance_11.material}
                  position={[810, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_12.geometry}
                  material={nodes.mesh_29_instance_12.material}
                  position={[891, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_29_instance_13.geometry}
                  material={nodes.mesh_29_instance_13.material}
                  position={[972, 0, 0]}
                />
              </group>
              <group
                position={[-429.33, -9.04, -196.64]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.mesh_44_instance_1.geometry}
                  material={nodes.mesh_44_instance_1.material}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_2.geometry}
                  material={nodes.mesh_44_instance_2.material}
                  position={[81, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_3.geometry}
                  material={nodes.mesh_44_instance_3.material}
                  position={[162, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_4.geometry}
                  material={nodes.mesh_44_instance_4.material}
                  position={[243, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_5.geometry}
                  material={nodes.mesh_44_instance_5.material}
                  position={[324, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_6.geometry}
                  material={nodes.mesh_44_instance_6.material}
                  position={[405, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_7.geometry}
                  material={nodes.mesh_44_instance_7.material}
                  position={[486, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_8.geometry}
                  material={nodes.mesh_44_instance_8.material}
                  position={[567, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_9.geometry}
                  material={nodes.mesh_44_instance_9.material}
                  position={[648, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_10.geometry}
                  material={nodes.mesh_44_instance_10.material}
                  position={[729, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_11.geometry}
                  material={nodes.mesh_44_instance_11.material}
                  position={[810, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_12.geometry}
                  material={nodes.mesh_44_instance_12.material}
                  position={[891, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_44_instance_13.geometry}
                  material={nodes.mesh_44_instance_13.material}
                  position={[972, 0, 0]}
                />
              </group>
              <group
                position={[-549.33, -9.04, -118.99]}
                rotation={[-Math.PI / 2, 0, 0]}
              >
                <mesh
                  geometry={nodes.mesh_45_instance_1.geometry}
                  material={nodes.mesh_45_instance_1.material}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_2.geometry}
                  material={nodes.mesh_45_instance_2.material}
                  position={[81, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_3.geometry}
                  material={nodes.mesh_45_instance_3.material}
                  position={[162, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_4.geometry}
                  material={nodes.mesh_45_instance_4.material}
                  position={[243, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_5.geometry}
                  material={nodes.mesh_45_instance_5.material}
                  position={[324, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_6.geometry}
                  material={nodes.mesh_45_instance_6.material}
                  position={[405, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_7.geometry}
                  material={nodes.mesh_45_instance_7.material}
                  position={[486, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_8.geometry}
                  material={nodes.mesh_45_instance_8.material}
                  position={[567, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_9.geometry}
                  material={nodes.mesh_45_instance_9.material}
                  position={[648, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_10.geometry}
                  material={nodes.mesh_45_instance_10.material}
                  position={[729, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_11.geometry}
                  material={nodes.mesh_45_instance_11.material}
                  position={[810, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_12.geometry}
                  material={nodes.mesh_45_instance_12.material}
                  position={[891, 0, 0]}
                />
                <mesh
                  geometry={nodes.mesh_45_instance_13.geometry}
                  material={nodes.mesh_45_instance_13.material}
                  position={[972, 0, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Torus.geometry}
                material={nodes.Torus.material}
                position={[542.48, -3.08, -197.92]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.17}
              />
              <mesh
                geometry={nodes.keybord_lign.geometry}
                material={nodes.keybord_lign.material}
                position={[306.67, -9.04, 198.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keybord_lign_1.geometry}
                material={nodes.keybord_lign_1.material}
                position={[-550.66, -9.04, 198.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keybord_lign_2.geometry}
                material={nodes.keybord_lign_2.material}
                position={[-364.4, -9.04, 120.03]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keybord_lign_3.geometry}
                material={nodes.keybord_lign_3.material}
                position={[-405.8, -9.04, 40.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keybord_lign_4.geometry}
                material={nodes.keybord_lign_4.material}
                position={[-429.33, -9.04, -40.64]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_6.geometry}
                material={nodes.Rectangle_6.material}
                position={[-39.25, -9.04, 198.26]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_7.geometry}
                material={nodes.Rectangle_7.material}
                position={[214.76, -9.04, 198.26]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_5.geometry}
                material={nodes.Rectangle_5.material}
                position={[-293.93, -9.04, 198.26]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_14.geometry}
                material={nodes.Rectangle_14.material}
                position={[466.16, -8.97, 180.77]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1, 1, 2.67]}
              />
              <mesh
                geometry={nodes.Rectangle_13.geometry}
                material={nodes.Rectangle_13.material}
                position={[466.16, -8.97, 215.5]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1, 1, 2.67]}
              />
              <mesh
                geometry={nodes.Rectangle_12.geometry}
                material={nodes.Rectangle_12.material}
                position={[548.77, -8.97, 215.5]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1, 1, 2.67]}
              />
              <mesh
                geometry={nodes.Rectangle_11.geometry}
                material={nodes.Rectangle_11.material}
                position={[386.57, -8.97, 215.5]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1, 1, 2.67]}
              />
              <mesh
                geometry={nodes.Rectangle_8.geometry}
                material={nodes.Rectangle_8.material}
                position={[494.68, -9.04, 120.42]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_4.geometry}
                material={nodes.Rectangle_4.material}
                position={[-499.8, -9.04, 120.42]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_9.geometry}
                material={nodes.Rectangle_9.material}
                position={[513.92, -9.04, 40.9]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_3_1.geometry}
                material={nodes.Rectangle_3_1.material}
                position={[-519.3, -9.04, 40.9]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_10.geometry}
                material={nodes.Rectangle_10.material}
                position={[523.26, -9.04, -119.43]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_2_1.geometry}
                material={nodes.Rectangle_2_1.material}
                position={[-530.8, -9.04, -40.8]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_15.geometry}
                material={nodes.Rectangle_15.material}
                position={[-529.3, -9.04, -196.64]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keybord_lign_5.geometry}
                material={nodes.keybord_lign_5.material}
                position={[-429.33, -9.04, -196.64]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keybord_lign_6.geometry}
                material={nodes.keybord_lign_6.material}
                position={[-549.33, -9.04, -118.99]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <mesh
                geometry={nodes.keyboard_1.geometry}
                material={nodes.keyboard_1.material}
                position={[0, -7.7, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1, 1, 2.16]}
              />
              <mesh
                geometry={nodes.mesh_25_instance_1.geometry}
                material={nodes.mesh_25_instance_1.material}
                position={[306.67, -9.04, 198.69]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              position={[-4.13, 34.51, -285]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.trackpad_top.geometry}
                material={nodes.trackpad_top.material}
                position={[-61.19, -1.67, -41.26]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.83, 0.83, 5]}
              />
              <mesh
                geometry={nodes.trackpad_border.geometry}
                material={nodes.trackpad_border.material}
                position={[-61.19, -2.48, -41.26]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[0.83, 0.83, 5]}
              />
            </group>
            <group
              position={[-633.05, 12.57, 270.94]}
              rotation={[-Math.PI, 0, -Math.PI]}
            >
              <mesh
                geometry={nodes.Rectangle_9_1.geometry}
                material={nodes.Rectangle_9_1.material}
                position={[-2.05, -20.27, 425.43]}
                rotation={[Math.PI / 2, 1.28, -Math.PI / 2]}
              />
              <mesh
                geometry={nodes.Rectangle_10_1.geometry}
                material={nodes.Rectangle_10_1.material}
                position={[0, 0, -105.07]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_9_2.geometry}
                material={nodes.Rectangle_9_2.material}
                position={[0, 2.5, -26.07]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_8_1.geometry}
                material={nodes.Rectangle_8_1.material}
                position={[0, 2.94, 79.57]}
                rotation={[0, Math.PI / 2, 0]}
              />
            </group>
            <group position={[745.73, 14.04, 293.61]}>
              <mesh
                geometry={nodes.Rectangle_8_2.geometry}
                material={nodes.Rectangle_8_2.material}
                position={[-1.38, -18.91, -448.11]}
                rotation={[Math.PI / 2, 1.23, -Math.PI / 2]}
              />
              <mesh
                geometry={nodes.Rectangle_3_2.geometry}
                material={nodes.Rectangle_3_2.material}
                position={[0.77, 1.08, 84]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Ellipse.geometry}
                material={nodes.Ellipse.material}
                position={[0.48, -0.08, -113.5]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_6_1.geometry}
                material={nodes.Rectangle_6_1.material}
                position={[0.48, 0.57, -58.94]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_5_1.geometry}
                material={nodes.Rectangle_5_1.material}
                position={[0.48, 0.57, 5.16]}
                rotation={[0, Math.PI / 2, 0]}
              />
              <mesh
                geometry={nodes.Rectangle_4_1.geometry}
                material={nodes.Rectangle_4_1.material}
                position={[0.48, 1.08, 84]}
                rotation={[0, Math.PI / 2, 0]}
              />
            </group>
            <mesh
              geometry={nodes.Cube.geometry}
              material={nodes.Cube.material}
              position={[56.34, 17.75, 516.41]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={2.07}
            />
          </group>
          <pointLight
            intensity={1.9}
            decay={2}
            distance={2000}
            color="#d591ff"
            position={[-260.19, 737.2, 1655.59]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={2.07}
          />
          <pointLight
            intensity={1.9}
            decay={2}
            distance={2000}
            color="#ffb9f7"
            position={[-285.4, -58.2, -10.11]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={2.07}
          />
          <pointLight
            intensity={1.9}
            decay={2}
            distance={2000}
            color="#b76aff"
            position={[0, -58.2, -10.11]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={2.07}
          />
        </group>
        <OrthographicCamera
          makeDefault={false}
          far={50000}
          near={0}
          position={[40.96, 1.22, 1000]}
        >
          <directionalLight intensity={0.6} rotation={[-0.7, 0.65, 0.95]} />
        </OrthographicCamera>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[40.96, 1.22, 1000]}
        />
        <mesh
          geometry={nodes.Rectangle.geometry}
          material={nodes.Rectangle.material}
          position={[0, -359.01, 20.52]}
          rotation={[-1.49, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/laptop.gltf");
