import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en" data-theme="custom-dark">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="overflow-x-hidden font-raleway">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
